# Generated by Django 4.2.6 on 2023-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phar',
            name='entry',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECT', 'REJECT')], default='PENDING', max_length=20),
        ),
    ]
