# Generated by Django 4.2.6 on 2024-01-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
