# Generated by Django 4.2.6 on 2024-01-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_login_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phar',
            new_name='Pharmacy',
        ),
    ]
